<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev;

use \php\Boot;

class MagLevArray extends MagLevAny {
	/**
	 * @var \Array_hx
	 */
	public $values;

	/**
	 * @return MagLevArray
	 */
	public static function create () {
		#/src/maglev/MagLevTypes.hx:300: characters 9-33
		return new MagLevArray();
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#/src/maglev/MagLevTypes.hx:303: characters 9-40
		$this->values = new \Array_hx();
		#/src/maglev/MagLevTypes.hx:304: characters 9-16
		parent::__construct();
	}

	/**
	 * @param int $i
	 * 
	 * @return MagLevAny
	 */
	public function get ($i) {
		#/src/maglev/MagLevTypes.hx:326: characters 9-42
		return MagLevNull::wrap(($this->values->arr[$i] ?? null));
	}

	/**
	 * @return MagLevType
	 */
	public function getType () {
		#/src/maglev/MagLevTypes.hx:332: characters 9-32
		return MagLevType::MagLevType_Array();
	}

	/**
	 * @param MagLevAny $other
	 * 
	 * @return bool
	 */
	public function isEqual ($other) {
		#/src/maglev/MagLevTypes.hx:335: lines 335-356
		if ($other->getType() === $this->getType()) {
			#/src/maglev/MagLevTypes.hx:336: characters 13-46
			$o = Boot::typedCast(Boot::getClass(MagLevArray::class), $other);
			#/src/maglev/MagLevTypes.hx:337: lines 337-352
			if ($this->size() === $o->size()) {
				#/src/maglev/MagLevTypes.hx:338: characters 17-64
				$arr = Boot::typedCast(Boot::getClass(MagLevArray::class), $other);
				#/src/maglev/MagLevTypes.hx:339: lines 339-347
				$_g = 0;
				$_g1 = $this->values;
				while ($_g < $_g1->length) {
					#/src/maglev/MagLevTypes.hx:339: characters 22-26
					$item = ($_g1->arr[$_g] ?? null);
					#/src/maglev/MagLevTypes.hx:339: lines 339-347
					++$_g;
					#/src/maglev/MagLevTypes.hx:340: characters 21-44
					$found = false;
					#/src/maglev/MagLevTypes.hx:341: lines 341-345
					$_g2 = 0;
					$_g3 = $arr->values;
					while ($_g2 < $_g3->length) {
						#/src/maglev/MagLevTypes.hx:341: characters 26-31
						$item2 = ($_g3->arr[$_g2] ?? null);
						#/src/maglev/MagLevTypes.hx:341: lines 341-345
						++$_g2;
						#/src/maglev/MagLevTypes.hx:342: lines 342-344
						if ($item->isEqual($item2)) {
							#/src/maglev/MagLevTypes.hx:343: characters 29-41
							$found = true;
						}
					}
					#/src/maglev/MagLevTypes.hx:346: characters 21-45
					if (!$found) {
						#/src/maglev/MagLevTypes.hx:346: characters 33-45
						return false;
					}
				}
				#/src/maglev/MagLevTypes.hx:348: characters 17-28
				return true;
			} else {
				#/src/maglev/MagLevTypes.hx:351: characters 17-29
				return false;
			}
		} else {
			#/src/maglev/MagLevTypes.hx:355: characters 13-25
			return false;
		}
	}

	/**
	 * @return MagLevAny
	 */
	public function pop () {
		#/src/maglev/MagLevTypes.hx:310: characters 32-44
		$_this = $this->values;
		if ($_this->length > 0) {
			$_this->length--;
		}
		#/src/maglev/MagLevTypes.hx:310: characters 9-45
		return MagLevNull::wrap(array_pop($_this->arr));
	}

	/**
	 * @param MagLevAny $x
	 * 
	 * @return int
	 */
	public function push ($x) {
		#/src/maglev/MagLevTypes.hx:313: characters 9-23
		$_this = $this->values;
		$_this->arr[$_this->length++] = $x;
		#/src/maglev/MagLevTypes.hx:314: characters 9-22
		return $this->size();
	}

	/**
	 * @return void
	 */
	public function reverse () {
		#/src/maglev/MagLevTypes.hx:323: characters 9-25
		$_this = $this->values;
		$_this->arr = array_reverse($_this->arr);
	}

	/**
	 * @param int $i
	 * @param MagLevAny $value
	 * 
	 * @return void
	 */
	public function set ($i, $value) {
		#/src/maglev/MagLevTypes.hx:329: characters 9-43
		$this->values->offsetSet($i, MagLevNull::wrap($value));
	}

	/**
	 * @return MagLevAny
	 */
	public function shift () {
		#/src/maglev/MagLevTypes.hx:317: characters 32-46
		$_this = $this->values;
		if ($_this->length > 0) {
			$_this->length--;
		}
		#/src/maglev/MagLevTypes.hx:317: characters 9-47
		return MagLevNull::wrap(array_shift($_this->arr));
	}

	/**
	 * @return int
	 */
	public function size () {
		#/src/maglev/MagLevTypes.hx:307: characters 9-29
		return $this->values->length;
	}

	/**
	 * @return MagLevString
	 */
	public function toJson () {
		#/src/maglev/MagLevTypes.hx:359: characters 9-28
		$s = "[";
		#/src/maglev/MagLevTypes.hx:360: characters 9-31
		$first = true;
		#/src/maglev/MagLevTypes.hx:361: lines 361-367
		$_g = 0;
		$_g1 = $this->values;
		while ($_g < $_g1->length) {
			#/src/maglev/MagLevTypes.hx:361: characters 14-18
			$item = ($_g1->arr[$_g] ?? null);
			#/src/maglev/MagLevTypes.hx:361: lines 361-367
			++$_g;
			#/src/maglev/MagLevTypes.hx:362: lines 362-364
			if (!$first) {
				#/src/maglev/MagLevTypes.hx:363: characters 17-26
				$s = ($s??'null') . ", ";
			}
			#/src/maglev/MagLevTypes.hx:365: characters 13-43
			$s = ($s??'null') . ($item->toJson()->getString()??'null');
			#/src/maglev/MagLevTypes.hx:366: characters 13-26
			$first = false;
		}
		#/src/maglev/MagLevTypes.hx:368: characters 9-17
		$s = ($s??'null') . "]";
		#/src/maglev/MagLevTypes.hx:369: characters 9-35
		return new MagLevString($s);
	}

	/**
	 * @param MagLevAny $x
	 * 
	 * @return void
	 */
	public function unshift ($x) {
		#/src/maglev/MagLevTypes.hx:320: characters 9-43
		$_this = $this->values;
		$x1 = MagLevNull::wrap($x);
		$_this->length = array_unshift($_this->arr, $x1);
	}
}

Boot::registerClass(MagLevArray::class, 'maglev.MagLevArray');
