<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev;

use \php\Boot;

class MagLevNull extends MagLevAny {
	/**
	 * @return MagLevNull
	 */
	public static function create () {
		#/src/maglev/MagLevTypes.hx:480: characters 9-32
		return new MagLevNull();
	}

	/**
	 * @param MagLevAny $o
	 * 
	 * @return MagLevAny
	 */
	public static function wrap ($o) {
		#/src/maglev/MagLevTypes.hx:500: lines 500-504
		if ($o === null) {
			#/src/maglev/MagLevTypes.hx:501: characters 13-36
			return new MagLevNull();
		} else {
			#/src/maglev/MagLevTypes.hx:503: characters 13-21
			return $o;
		}
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#/src/maglev/MagLevTypes.hx:483: characters 9-16
		parent::__construct();
	}

	/**
	 * @return MagLevType
	 */
	public function getType () {
		#/src/maglev/MagLevTypes.hx:486: characters 9-31
		return MagLevType::MagLevType_Null();
	}

	/**
	 * @param MagLevAny $other
	 * 
	 * @return bool
	 */
	public function isEqual ($other) {
		#/src/maglev/MagLevTypes.hx:489: lines 489-494
		if ($other->getType() === $this->getType()) {
			#/src/maglev/MagLevTypes.hx:490: characters 13-24
			return true;
		} else {
			#/src/maglev/MagLevTypes.hx:493: characters 13-25
			return false;
		}
	}

	/**
	 * @return MagLevString
	 */
	public function toJson () {
		#/src/maglev/MagLevTypes.hx:497: characters 9-40
		return new MagLevString("null");
	}
}

Boot::registerClass(MagLevNull::class, 'maglev.MagLevNull');
