<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev;

use \php\Boot;

class MagLevString extends MagLevAny {
	/**
	 * @var string
	 */
	public $value;

	/**
	 * @param string $value
	 * 
	 * @return MagLevString
	 */
	public static function fromString ($value) {
		#/src/maglev/MagLev.hx:588: characters 9-39
		return new MagLevString($value);
	}

	/**
	 * @return int
	 */
	public static function getStaticType () {
		#/src/maglev/MagLev.hx:601: characters 9-17
		return 3;
	}

	/**
	 * @param string $value
	 * 
	 * @return void
	 */
	public function __construct ($value) {
		#/src/maglev/MagLev.hx:591: characters 9-27
		$this->value = $value;
		#/src/maglev/MagLev.hx:592: characters 9-16
		parent::__construct();
	}

	/**
	 * @return string
	 */
	public function getString () {
		#/src/maglev/MagLev.hx:595: characters 9-26
		return $this->value;
	}

	/**
	 * @return int
	 */
	public function getType () {
		#/src/maglev/MagLev.hx:598: characters 9-17
		return 3;
	}

	/**
	 * @param MagLevAny $other
	 * 
	 * @return bool
	 */
	public function isEqual ($other) {
		#/src/maglev/MagLev.hx:604: lines 604-610
		if ($other->getType() === $this->getType()) {
			#/src/maglev/MagLev.hx:605: characters 13-47
			$o = Boot::typedCast(Boot::getClass(MagLevString::class), $other);
			#/src/maglev/MagLev.hx:606: characters 13-48
			return $this->getString() === $o->getString();
		} else {
			#/src/maglev/MagLev.hx:609: characters 13-25
			return false;
		}
	}

	/**
	 * @return MagLevString
	 */
	public function toJson () {
		#/src/maglev/MagLev.hx:613: characters 9-53
		return new MagLevString("\"" . ($this->value??'null') . "\"");
	}
}

Boot::registerClass(MagLevString::class, 'maglev.MagLevString');
