<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev;

use \php\Boot;
use \haxe\Exception;
use \haxe\ds\StringMap;

class MagLev {
	/**
	 * @var StringMap
	 */
	static public $_instances;

	/**
	 * @var StringMap
	 */
	public $_listeners;
	/**
	 * @var StringMap
	 */
	public $_methods;

	/**
	 * @param string $key
	 * 
	 * @return MagLev
	 */
	public static function getInstance ($key) {
		#/src/maglev/MagLev.hx:48: lines 48-50
		if (!array_key_exists($key, MagLev::$_instances->data)) {
			#/src/maglev/MagLev.hx:49: characters 5-35
			$this1 = MagLev::$_instances;
			$v = new MagLev();
			$this1->data[$key] = $v;
		}
		#/src/maglev/MagLev.hx:51: characters 10-25
		return (MagLev::$_instances->data[$key] ?? null);
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#/src/maglev/MagLev.hx:42: characters 63-112
		$this->_listeners = new StringMap();
		#/src/maglev/MagLev.hx:41: characters 45-78
		$this->_methods = new StringMap();
	}

	/**
	 * @param string $method
	 * @param \Array_hx $args
	 * 
	 * @return mixed
	 */
	public function call ($method, $args) {
		#/src/maglev/MagLev.hx:59: lines 59-63
		if (array_key_exists($method, $this->_methods->data)) {
			#/src/maglev/MagLev.hx:60: characters 13-42
			return ($this->_methods->data[$method] ?? null)($args);
		} else {
			#/src/maglev/MagLev.hx:62: characters 4-9
			throw Exception::thrown("Method '" . ($method??'null') . "' not registered");
		}
	}

	/**
	 * @param string $event
	 * @param \Array_hx $args
	 * 
	 * @return void
	 */
	public function emit ($event, $args) {
		#/src/maglev/MagLev.hx:75: lines 75-80
		if (array_key_exists($event, $this->_listeners->data)) {
			#/src/maglev/MagLev.hx:76: characters 4-38
			$listeners = ($this->_listeners->data[$event] ?? null);
			#/src/maglev/MagLev.hx:77: lines 77-79
			$_g = 0;
			while ($_g < $listeners->length) {
				#/src/maglev/MagLev.hx:77: characters 8-16
				$listener = ($listeners->arr[$_g] ?? null);
				#/src/maglev/MagLev.hx:77: lines 77-79
				++$_g;
				#/src/maglev/MagLev.hx:78: characters 5-26
				$listener($event, $args);
			}
		}
	}

	/**
	 * @param string $event
	 * @param \Closure $callback
	 * 
	 * @return void
	 */
	public function listen ($event, $callback) {
		#/src/maglev/MagLev.hx:68: lines 68-70
		if (!array_key_exists($event, $this->_listeners->data)) {
			#/src/maglev/MagLev.hx:69: characters 4-61
			$this1 = $this->_listeners;
			$v = new \Array_hx();
			$this1->data[$event] = $v;
		}
		#/src/maglev/MagLev.hx:71: characters 3-35
		$_this = ($this->_listeners->data[$event] ?? null);
		$_this->arr[$_this->length++] = $callback;
	}

	/**
	 * @param string $method
	 * @param \Closure $callback
	 * 
	 * @return void
	 */
	public function register ($method, $callback) {
		#/src/maglev/MagLev.hx:55: characters 3-30
		$this->_methods->data[$method] = $callback;
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$_instances = new StringMap();
	}
}

Boot::registerClass(MagLev::class, 'maglev.MagLev');
MagLev::__hx__init();
