<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev;

use \php\Boot;

class MagLevError {
	/**
	 * @var MagLevNumber
	 */
	public $code;
	/**
	 * @var MagLevAny
	 */
	public $data;
	/**
	 * @var MagLevString
	 */
	public $message;

	/**
	 * @param int $code
	 * @param string $message
	 * @param MagLevAny $data
	 * 
	 * @return MagLevError
	 */
	public static function create ($code, $message, $data) {
		#/src/maglev/MagLev.hx:222: characters 9-44
		$code2 = new MagLevNumber($code);
		#/src/maglev/MagLev.hx:223: characters 9-50
		$message2 = new MagLevString($message);
		#/src/maglev/MagLev.hx:224: characters 9-54
		return new MagLevError($code2, $message2, $data);
	}

	/**
	 * @return int
	 */
	public static function getStaticType () {
		#/src/maglev/MagLev.hx:244: characters 9-19
		return 100;
	}

	/**
	 * @param MagLevNumber $code
	 * @param MagLevString $message
	 * @param MagLevAny $data
	 * 
	 * @return void
	 */
	public function __construct ($code, $message, $data) {
		#/src/maglev/MagLev.hx:227: characters 9-25
		$this->code = $code;
		#/src/maglev/MagLev.hx:228: characters 9-31
		$this->message = $message;
		#/src/maglev/MagLev.hx:229: characters 9-25
		$this->data = $data;
	}

	/**
	 * @return int
	 */
	public function getCode () {
		#/src/maglev/MagLev.hx:232: characters 9-29
		return $this->code->getInt();
	}

	/**
	 * @return MagLevAny
	 */
	public function getData () {
		#/src/maglev/MagLev.hx:238: characters 9-20
		return $this->data;
	}

	/**
	 * @return string
	 */
	public function getMessage () {
		#/src/maglev/MagLev.hx:235: characters 9-35
		return $this->message->getString();
	}

	/**
	 * @return int
	 */
	public function getType () {
		#/src/maglev/MagLev.hx:241: characters 9-19
		return 100;
	}

	/**
	 * @param MagLevError $other
	 * 
	 * @return bool
	 */
	public function isEqual ($other) {
		#/src/maglev/MagLev.hx:248: characters 9-30
		$same = true;
		#/src/maglev/MagLev.hx:249: characters 24-71
		$same = $same && $this->code->isEqual(new MagLevNumber($other->getCode()));
		#/src/maglev/MagLev.hx:250: characters 24-77
		$same = $same && $this->message->isEqual(new MagLevString($other->getMessage()));
		#/src/maglev/MagLev.hx:251: characters 24-53
		$same = $same && $this->data->isEqual($other->getData());
		#/src/maglev/MagLev.hx:252: characters 9-20
		return $same;
	}

	/**
	 * @return MagLevString
	 */
	public function toJson () {
		#/src/maglev/MagLev.hx:255: characters 9-135
		return new MagLevString("{\"code\": " . (\Std::string($this->code->toJson())??'null') . ", \"message\": " . (\Std::string($this->message->toJson())??'null') . ", \"data\": " . (\Std::string($this->data->toJson())??'null') . "}");
	}
}

Boot::registerClass(MagLevError::class, 'maglev.MagLevError');
