<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev;

use \php\Boot;

class MagLevBoolean extends MagLevAny {
	/**
	 * @var bool
	 */
	public $value;

	/**
	 * @param bool $value
	 * 
	 * @return MagLevBoolean
	 */
	public static function fromBool ($value) {
		#/src/maglev/MagLev.hx:622: characters 9-40
		return new MagLevBoolean($value);
	}

	/**
	 * @return int
	 */
	public static function getStaticType () {
		#/src/maglev/MagLev.hx:635: characters 9-17
		return 2;
	}

	/**
	 * @param bool $value
	 * 
	 * @return void
	 */
	public function __construct ($value) {
		#/src/maglev/MagLev.hx:625: characters 9-27
		$this->value = $value;
		#/src/maglev/MagLev.hx:626: characters 9-16
		parent::__construct();
	}

	/**
	 * @return bool
	 */
	public function getBool () {
		#/src/maglev/MagLev.hx:629: characters 9-21
		return $this->value;
	}

	/**
	 * @return int
	 */
	public function getType () {
		#/src/maglev/MagLev.hx:632: characters 9-17
		return 2;
	}

	/**
	 * @param MagLevAny $other
	 * 
	 * @return bool
	 */
	public function isEqual ($other) {
		#/src/maglev/MagLev.hx:638: lines 638-644
		if ($other->getType() === $this->getType()) {
			#/src/maglev/MagLev.hx:639: characters 13-48
			$o = Boot::typedCast(Boot::getClass(MagLevBoolean::class), $other);
			#/src/maglev/MagLev.hx:640: characters 13-44
			return $this->getBool() === $o->getBool();
		} else {
			#/src/maglev/MagLev.hx:643: characters 13-25
			return false;
		}
	}

	/**
	 * @return MagLevString
	 */
	public function toJson () {
		#/src/maglev/MagLev.hx:647: lines 647-651
		if ($this->value) {
			#/src/maglev/MagLev.hx:648: characters 13-44
			return new MagLevString("true");
		} else {
			#/src/maglev/MagLev.hx:650: characters 13-45
			return new MagLevString("false");
		}
	}
}

Boot::registerClass(MagLevBoolean::class, 'maglev.MagLevBoolean');
