<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev;

use \php\Boot;

class MagLevNull extends MagLevAny {
	/**
	 * @return MagLevNull
	 */
	public static function create () {
		#/src/maglev/MagLev.hx:659: characters 9-32
		return new MagLevNull();
	}

	/**
	 * @return int
	 */
	public static function getStaticType () {
		#/src/maglev/MagLev.hx:668: characters 9-17
		return 1;
	}

	/**
	 * @param MagLevAny $o
	 * 
	 * @return MagLevAny
	 */
	public static function wrap ($o) {
		#/src/maglev/MagLev.hx:682: lines 682-686
		if ($o === null) {
			#/src/maglev/MagLev.hx:683: characters 13-36
			return new MagLevNull();
		} else {
			#/src/maglev/MagLev.hx:685: characters 13-21
			return $o;
		}
	}

	/**
	 * @return void
	 */
	public function __construct () {
		#/src/maglev/MagLev.hx:662: characters 9-16
		parent::__construct();
	}

	/**
	 * @return int
	 */
	public function getType () {
		#/src/maglev/MagLev.hx:665: characters 9-17
		return 1;
	}

	/**
	 * @param MagLevAny $other
	 * 
	 * @return bool
	 */
	public function isEqual ($other) {
		#/src/maglev/MagLev.hx:671: lines 671-676
		if ($other->getType() === $this->getType()) {
			#/src/maglev/MagLev.hx:672: characters 13-24
			return true;
		} else {
			#/src/maglev/MagLev.hx:675: characters 13-25
			return false;
		}
	}

	/**
	 * @return MagLevString
	 */
	public function toJson () {
		#/src/maglev/MagLev.hx:679: characters 9-40
		return new MagLevString("null");
	}
}

Boot::registerClass(MagLevNull::class, 'maglev.MagLevNull');
