<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev;

use \php\Boot;
use \maglev\_MagLev\MagLevType_Impl_;

class MagLevBoolean extends MagLevAny {
	/**
	 * @var bool
	 */
	public $value;

	/**
	 * @param bool $value
	 * 
	 * @return MagLevBoolean
	 */
	public static function fromBool ($value) {
		#/src/maglev/MagLev.hx:527: characters 9-40
		return new MagLevBoolean($value);
	}

	/**
	 * @param bool $value
	 * 
	 * @return void
	 */
	public function __construct ($value) {
		#/src/maglev/MagLev.hx:530: characters 9-27
		$this->value = $value;
		#/src/maglev/MagLev.hx:531: characters 9-16
		parent::__construct();
	}

	/**
	 * @return bool
	 */
	public function getBool () {
		#/src/maglev/MagLev.hx:534: characters 9-21
		return $this->value;
	}

	/**
	 * @return int
	 */
	public function getType () {
		#/src/maglev/MagLev.hx:537: characters 9-45
		return MagLevType_Impl_::$MagLevType_Boolean;
	}

	/**
	 * @param MagLevAny $other
	 * 
	 * @return bool
	 */
	public function isEqual ($other) {
		#/src/maglev/MagLev.hx:540: lines 540-546
		if ($other->getType() === $this->getType()) {
			#/src/maglev/MagLev.hx:541: characters 13-48
			$o = Boot::typedCast(Boot::getClass(MagLevBoolean::class), $other);
			#/src/maglev/MagLev.hx:542: characters 13-44
			return $this->getBool() === $o->getBool();
		} else {
			#/src/maglev/MagLev.hx:545: characters 13-25
			return false;
		}
	}

	/**
	 * @return MagLevString
	 */
	public function toJson () {
		#/src/maglev/MagLev.hx:549: lines 549-553
		if ($this->value) {
			#/src/maglev/MagLev.hx:550: characters 13-44
			return new MagLevString("true");
		} else {
			#/src/maglev/MagLev.hx:552: characters 13-45
			return new MagLevString("false");
		}
	}
}

Boot::registerClass(MagLevBoolean::class, 'maglev.MagLevBoolean');
