<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev;

use \php\Boot;

class MagLevBoolean extends MagLevAny {
	/**
	 * @var bool
	 */
	public $value;

	/**
	 * @param bool $value
	 * 
	 * @return MagLevBoolean
	 */
	public static function fromBool ($value) {
		#/src/maglev/MagLev.hx:577: characters 9-40
		return new MagLevBoolean($value);
	}

	/**
	 * @return int
	 */
	public static function getStaticType () {
		#/src/maglev/MagLev.hx:590: characters 9-17
		return 2;
	}

	/**
	 * @param bool $value
	 * 
	 * @return void
	 */
	public function __construct ($value) {
		#/src/maglev/MagLev.hx:580: characters 9-27
		$this->value = $value;
		#/src/maglev/MagLev.hx:581: characters 9-16
		parent::__construct();
	}

	/**
	 * @return bool
	 */
	public function getBool () {
		#/src/maglev/MagLev.hx:584: characters 9-21
		return $this->value;
	}

	/**
	 * @return int
	 */
	public function getType () {
		#/src/maglev/MagLev.hx:587: characters 9-17
		return 2;
	}

	/**
	 * @param MagLevAny $other
	 * 
	 * @return bool
	 */
	public function isEqual ($other) {
		#/src/maglev/MagLev.hx:593: lines 593-599
		if ($other->getType() === $this->getType()) {
			#/src/maglev/MagLev.hx:594: characters 13-48
			$o = Boot::typedCast(Boot::getClass(MagLevBoolean::class), $other);
			#/src/maglev/MagLev.hx:595: characters 13-44
			return $this->getBool() === $o->getBool();
		} else {
			#/src/maglev/MagLev.hx:598: characters 13-25
			return false;
		}
	}

	/**
	 * @return MagLevString
	 */
	public function toJson () {
		#/src/maglev/MagLev.hx:602: lines 602-606
		if ($this->value) {
			#/src/maglev/MagLev.hx:603: characters 13-44
			return new MagLevString("true");
		} else {
			#/src/maglev/MagLev.hx:605: characters 13-45
			return new MagLevString("false");
		}
	}
}

Boot::registerClass(MagLevBoolean::class, 'maglev.MagLevBoolean');
