<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev;

use \php\Boot;

class MagLevFunction extends MagLevAny {
	/**
	 * @var string
	 */
	public $name;
	/**
	 * @var \Closure
	 */
	public $value;

	/**
	 * @param \Closure $value
	 * 
	 * @return MagLevFunction
	 */
	public static function fromFunction ($value) {
		#/src/maglev/MagLev.hx:283: characters 9-41
		return new MagLevFunction($value);
	}

	/**
	 * @param \Closure $value
	 * @param string $name
	 * 
	 * @return MagLevFunction
	 */
	public static function fromNamedFunction ($value, $name) {
		#/src/maglev/MagLev.hx:286: characters 9-47
		return new MagLevFunction($value, $name);
	}

	/**
	 * @return int
	 */
	public static function getStaticType () {
		#/src/maglev/MagLev.hx:306: characters 9-19
		return 200;
	}

	/**
	 * @param \Closure $value
	 * @param string $name
	 * 
	 * @return void
	 */
	public function __construct ($value, $name = null) {
		#/src/maglev/MagLev.hx:289: characters 9-25
		$this->name = $name;
		#/src/maglev/MagLev.hx:290: characters 9-27
		$this->value = $value;
		#/src/maglev/MagLev.hx:291: characters 9-16
		parent::__construct();
	}

	/**
	 * @param MagLevArray $args
	 * 
	 * @return MagLevResult
	 */
	public function call ($args) {
		#/src/maglev/MagLev.hx:294: characters 9-27
		return ($this->value)($args);
	}

	/**
	 * @return string
	 */
	public function getName () {
		#/src/maglev/MagLev.hx:300: characters 9-20
		return $this->name;
	}

	/**
	 * @return int
	 */
	public function getType () {
		#/src/maglev/MagLev.hx:303: characters 9-19
		return 200;
	}

	/**
	 * @return bool
	 */
	public function hasName () {
		#/src/maglev/MagLev.hx:297: characters 9-28
		return $this->name !== null;
	}

	/**
	 * @param MagLevAny $other
	 * 
	 * @return bool
	 */
	public function isEqual ($other) {
		#/src/maglev/MagLev.hx:309: lines 309-320
		if ($other->getType() === $this->getType()) {
			#/src/maglev/MagLev.hx:310: characters 13-49
			$o = Boot::typedCast(Boot::getClass(MagLevFunction::class), $other);
			#/src/maglev/MagLev.hx:311: lines 311-316
			if ($this->hasName() && $o->hasName()) {
				#/src/maglev/MagLev.hx:312: characters 17-48
				return $this->getName() === $o->getName();
			} else {
				#/src/maglev/MagLev.hx:315: characters 17-29
				return false;
			}
		} else {
			#/src/maglev/MagLev.hx:319: characters 13-25
			return false;
		}
	}

	/**
	 * @return MagLevString
	 */
	public function toJson () {
		#/src/maglev/MagLev.hx:323: lines 323-328
		if ($this->hasName()) {
			#/src/maglev/MagLev.hx:324: characters 13-63
			return new MagLevString("<function " . ($this->name??'null') . ">");
		} else {
			#/src/maglev/MagLev.hx:327: characters 13-51
			return new MagLevString("<anon func>");
		}
	}
}

Boot::registerClass(MagLevFunction::class, 'maglev.MagLevFunction');
