<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace maglev\_MagLev;

use \php\Boot;

final class MagLevType_Impl_ {
	/**
	 * @var int
	 */
	static public $MagLevType_Array;
	/**
	 * @var int
	 */
	static public $MagLevType_Boolean;
	/**
	 * @var int
	 */
	static public $MagLevType_Error;
	/**
	 * @var int
	 */
	static public $MagLevType_Function;
	/**
	 * @var int
	 */
	static public $MagLevType_Null;
	/**
	 * @var int
	 */
	static public $MagLevType_Number;
	/**
	 * @var int
	 */
	static public $MagLevType_Object;
	/**
	 * @var int
	 */
	static public $MagLevType_Result;
	/**
	 * @var int
	 */
	static public $MagLevType_String;

	/**
	 * @param int $i
	 * 
	 * @return int
	 */
	public static function _new ($i) {
		#/src/maglev/MagLev.hx:112: character 5
		$this1 = $i;
		return $this1;
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		$this1 = 11;
		self::$MagLevType_Result = $this1;
		$this1 = 10;
		self::$MagLevType_Error = $this1;
		$this1 = 20;
		self::$MagLevType_Function = $this1;
		$this1 = 5;
		self::$MagLevType_Object = $this1;
		$this1 = 4;
		self::$MagLevType_Array = $this1;
		$this1 = 3;
		self::$MagLevType_Number = $this1;
		$this1 = 2;
		self::$MagLevType_String = $this1;
		$this1 = 1;
		self::$MagLevType_Boolean = $this1;
		$this1 = 0;
		self::$MagLevType_Null = $this1;
	}
}

Boot::registerClass(MagLevType_Impl_::class, 'maglev._MagLev.MagLevType_Impl_');
MagLevType_Impl_::__hx__init();
